hola(juan).
hija(raquel,teresa).
hijo(miguel,raquel).
progenitor(pedro,teresa).
progenitor(maria,teresa).
progenitor(maria,elena).
progenitor(teresa,jorge).
progenitor(teresa,raquel).
progenitor(raquel,miguel).
mujer(raquel).
mujer(teresa).
mujer(elena).
mujer(maria).
hombre(pedro).
hombre(miguel).
hombre(jorge).
hombre(juan).
hombre(jose).
descendiente(Y,X):-progenitor(X,Y).
madre(X,W):-progenitor(X,W),mujer(X).
abuelo(X,Z):-progenitor(X,W),progenitor(W,Z),hombre(X).
hermana(X,W):-progenitor(Z,X),progenitor(Z,W),mujer(X).
hermano(X,W):-progenitor(Z,X),progenitor(Z,W),hombre(X).
padre(X,W):-progenitor(X,W),hombre(X).
antepasado(X,Z):-progenitor(X,Z).
antepasado(X,Z):- progenitor(X,W),antepasado(W,Z).
tia(X,Z):-progenitor(W,Z),hermana(X,W).
tio(X,Z):-progenitor(W,Z),hermano(X,W).
sobrino(X,Z):-hermana(W,Z),progenitor(W,X),hombre(X).
